#!/usr/bin/env ruby

line = `star -1d | dmenu-dropdown`.strip
if (line.length > 0)
  handler = `#{__dir__}/plumber-handlers`.chomp
  if (handler.length > 0)
    val = line.gsub(/{tags: [^}]+}/, '').strip
    system("echo \"#{val}\" | #{__dir__}/plumber #{handler}")
  end
end
